modLoader="kotlinforforge"
loaderVersion="[3,)"
license="Code - MIT, Content - CC0"
issueTrackerURL="https://github.com/age-series/SecurityAge/issues" #optional

[[mods]]
modId="securityage"
version="${file.jarVersion}"
displayName="Security Age"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://age-series.org/"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile=""
credits="The Age Series Team"
authors="BomberPlays, jrddunbr"

description='''
Security Age: To secure your bases, chests, and doors!
'''

[[dependencies.securityage]]
modId="forge"
mandatory=true
versionRange="[38,)"
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
[[dependencies.securityage]]
modId="minecraft"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"
